### ISSUE TITLE
Question: Flatten / sideload nested relationships at the top level

### ISSUE THREAD

**Issue by dwaltrip** [marshmallow-code/marshmallow#1148]
I apologize if this question is already clearly answered, but I wasn't able to find an answer in the docs or any issues.

Say I have two models that are related:

```
Book:
  id: primary-key integer
  name: string
  author_id: foreign-key Author.id

Author:
  id: primary-key integer
  name: string
```

I'd like to serialize a list of books and their authors, but have the authors as a flat list at the top. Something like this:

```
{
  "books": [
    { "id": 1, "name": "Book 1", "author_id": 1 },
    { "id": 2, "name": "Book 2", "author_id": 2 },
    { "id": 13 "name": "Book 3", "author_id": 1 },
  ],
  "authors": [
        { "id": 1, "name": "Joe Tzu" },
        { "id": 2, "name": "Melanie Smith" },
  ]
}
```

They key point is that there isn't any duplication of the author data, like there would be with a naive nesting. What would be the best way to do this with Marshmallow?

My real situation is a bit more complex with more levels. Something like A has many B, and B has many C, and we want a flat list of C at the top to prevent duplication of data (B could be flattened or not, in my case it doesn't matter).
