### ISSUE TITLE
Python2 to Python3, what is implicit under the hood?

### ISSUE THREAD

**Issue by tshawn2014** [marshmallow-code/marshmallow#2095]
I am trying to migrate my project from Python2(marshmallow 2.18.2) to Python3(marshmallow 3.19.0). There is a huge difference while the logic remains the same. The schema looks like the following abstractly:

```
        cells = fields.List(fields.Dict, missing=[])
        slots = fields.Dict(missing={})
```
slots has partial duplicated cells in its dict. `slots.get(slot_id)["cells"]`
In Python2, the duplicate changes as its source changes like reference, the yaml file looks like:
```
cells:
- &id001
    uid: 1
    number: 1
- &id002
    uid: 2
    number: 2
...
...
slots:
   cells:
      - *id001
      - *id002
```
When I edit cells[1]["number"] to 100, the value I get from slots["cells"][1]["number"] also becomes 100. It is the pointer referring to the cells defined earlier. (a shallow copy)

In Python3, the `id00x` lines are all gone, and the change in cells doesn't affect the duplicate inside slots, they are totally independent:
```
cells:
- uid: 1
   number: 1
- uid: 2
   number: 100
...
...
slots:
   cells:
      - uid: 1
         number: 1
      - uid: 2
         number: 2
```
When I edit cells[1]["number"] to 100, the value I get from slots["cells"][1]["number"] remains 2, as if they are 2 different object ( a deep copy)

Is there anything I am missing in the schema config or any code changes resulted in this ?
